### ISSUE TITLE
Klassen krijgen geen link

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Vocabularia#2]
Het is niet mogelijk om te zien welke URI er dient gebruikt te worden voor de klassen van de profielen.

Bvb: Wat is de URI voor [Agent](http://data.vlaanderen.be/doc/applicatieprofiel/organisatie#Agent)?

**Comment by jensscheerlinck** [comment]
Pull request voor OSLO Specgen tool waaraan dit wordt toegevoegd: 
https://github.com/Informatievlaanderen/OSLO-SpecificationGenerator/pull/3

Voorbeeld output:
https://github.com/Informatievlaanderen/OSLO-Vocabularia/blob/draft/doc/ap/persoon/persoon-burgerloket-ap.html
