### ISSUE TITLE
Geen link naar hergebruikte termen in vocabularia

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Vocabularia#3]
In de HTML specificaties van de vocabularia worden enkel de namespaces opgenomen van de hergebruikte vocabularia. Het is echter momenteel niet mogelijk om ook te zien welke klassen en eigenschappen precies werden overgenomen.

Voor klassen valt dit nog gedeeltelijk af te leiden uit het domein van de opgelijste eigenschappen.

Een mogelijkheid is om net zoals bij de [Web Annotation Vocabulary](https://www.w3.org/TR/annotation-vocab/) een sectie te voorzien met [Recommended Ontologies](https://www.w3.org/TR/annotation-vocab/#recommended-ontologies) (of in dit geval hergebruikte).

**Comment by DieterDePaepe** [comment]
Dit is zo bedoeld. De vocabularia geven enkel definities van nieuwe termen maar doen geen uitspraak over hoe andere vocabularia termen te gebruiken, daarvoor zijn de applicatie profielen er.

Zie je dit als een tekort van de vocabularia?

**Comment by jensscheerlinck** [comment]
Indien #2 opgelost wordt zie ik dit niet echt als een tekortkoming, eerder als een 'could have' feature voor mensen (buiten de Vlaamse Overheid) die geïnteresseerd zijn om de vocabularia te hergebruiken.
