### ISSUE TITLE
Klassen zonder attributen worden niet opgelijst in AP

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Vocabularia#37]
Voorbeeld: Oprichting in [organisatie AP](http://data.vlaanderen.be/doc/applicatieprofiel/organisatie), of #7.

/cc @laurensdv

**Comment by laurensdv** [comment]
Dit is de bedoeling,  de AP beschrijft beschrijftvoor elke uitgewisselde entiteit  welke attributen en relaties verwacht worden, welke optioneel zijn enz.

Indien er een entiteit opgenomen is in het model zonder attributen wordt dit verondersteld 'vrij' te zitten of een URI/document te zijn waarbij het niet uitmaakt wat erachter zit. 

Het is dan de relatie naar Oprichting in dit geval die moet duidelijk maken hoe deze entiteit gebruikt moet worden.

Indien Oprichting toch moet opgenomen worden in het AP, dan is het best om een aantal evidente (optionele) attributen toe te voegen die men daar kan verwachten, bvb. oprichtingsdatum.

**Comment by DieterDePaepe** [comment]
Bij bijvoorbeeld oprichting zitten de attributen in een superklasse.

Dit issue zou wellicht opgelost zijn als #26 opgelost raakt.

**Comment by laurensdv** [comment]
Inderdaad, de vraag is of we in een 'regel' kunnen gieten dat een subklasse steeds regels van de superklasse overerft, in dit geval zouden we die kunnen laten kopieren of een verwijzing zetten: "zie ook de superklasse"

**Comment by jensscheerlinck** [comment]
Geïmplementeerd in laatste versie van SpecGen tool.
