### ISSUE TITLE
vann:usageNote is subproperty van rdfs:seeAlso en dus verwacht als range een Resource, geen Literal

### ISSUE THREAD

**Issue by laurensdv** [Informatievlaanderen/OSLO-Vocabularia#38]
Zie: http://vocab.org/vann/#usageNote

en https://www.w3.org/TR/rdf-schema/#ch_seealso

Alternatieve property zoeken?

**Comment by DieterDePaepe** [comment]
Literals zijn subklasse van Resource: https://www.w3.org/TR/rdf-schema/#h3_ch_literal

Dus het is correct om Literals te gebruiken.

**Comment by laurensdv** [comment]
Ah, juist, inderdaad, maar goed ook en seeAlso maakt eigenlijk idd geen expliciete keuze tussen literal of niet (een rdf:Property en niet Objectproperty of Datatypeproperty).
