### ISSUE TITLE
Package "External"

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO-Vocabularia#43]
In het LBLOD klassediagram wordt verwezen naar elementen uit andere packages, bv Mandaat. Echter voor elementen afkomstig uit de basisdomeinen van OSLO (bv Organisatie, Generiek etc) wordt verwezen naar een package External. Bij het invoeren van LBLOD in de EnterpriseArchitect-repository gaan we alle verwijzingen moeten vervangen door verwijzingen naar de packages waaruit de elementen afkomstig zijn.

**Comment by DieterDePaepe** [comment]
Voor de vocabularia schema klopt dit. Voor de applicatie profielen weet ik het niet, gezien we daar toch al met kopieën werken...

**Comment by GeertThijs** [comment]
Inderdaad moeten vooral voor de VOC's de begrippen in de juiste namespace worden geplaatst. Voor de AP's echter vind ik het duidelijker als ipv External er Organisatie of Adres als voorvoegsel verschijnt voor de externe elementen.
