### ISSUE TITLE
Taalstring vs Langstring

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO-Vocabularia#44]
IN OSLO hebben we recent Taalstring als datatype ingevoerd. Ik veronderstel dat we ih LBLOD de LangString mogen vervangen door Taalstring?

**Comment by DieterDePaepe** [comment]
Inderdaad, ´LangString´ zit ingebakken in de tooling, `TaalString` is iets dat jij voor OSLO hebt gedefinieerd, maar ze mappen beide op hetzelfde.

**Comment by GeertThijs** [comment]
LBLOD aangepast.
