### ISSUE TITLE
Naamgevingsconventies

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO-Vocabularia#48]
Is er bewust afgeweken vd conventie in OSLO om klassen UpperCamelCase en eigenschappen lowerCamelCase te doen? Ik bedoel: Legale Verschijningsvorm vsLegaleVerschijningsvorm en niet gepland openbaar vs geplandOpenbaar. Moeten we afstappen van die conventie in OSLO of passen we LBLOD aan?

**Comment by DieterDePaepe** [comment]
In LBLOD komen de namen in de schema's overeen met de benamingen (labels) die opgelijst staan in de documentatie. Het schema was zo gegroeid zonder er echt bewust van te zijn dat we afweken van de OSLO conventie.

Ik heb al hier en daar gemerkt dat een verschil in termen in het schema en de documentatie voor verwarring kan zorgen, dus dit lijkt me wel iets om over na te denken. Was er een specifieke reden van de huidige conventie?

**Comment by GeertThijs** [comment]
Lijkt intussen in orde.
