### ISSUE TITLE
Hash URIs vocabularium Persoon

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Vocabularia#6]
In de HTML specificaties voor het vocabularium [Persoon](http://data.vlaanderen.be/ns/persoon) zijn de hash URIs als volgt meegegeven:

http://data.vlaanderen.be/ns/persoon#http://data.vlaanderen.be/ns/persoon#Afstamming

```HTML
<h3 class="h3" id="http://data.vlaanderen.be/ns/persoon#Afstamming">Klasse <em>Afstamming</em></h3>
```

->

```HTML
<h3 class="h3" id="Afstamming">Klasse <em>Afstamming</em></h3>
```

Zie pull request #4

**Comment by laurensdv** [comment]
Dit wordt gefixed in de volgende versie.
