### ISSUE TITLE
[question] AP Adresregister: Relatie Adres - Adresvoorstelling is many to one

### ISSUE THREAD

**Issue by YvesMeersmans** [Informatievlaanderen/OSLO-Vocabularia#65]
In het huidige AP Adresregister (zie afbeelding 1) verwijst het dataType Adresvoorstelling naar 0..* (many) (Belgisch) Adres objecten. Met welke redenering is dit zo gemodelleerd?

_afbeelding 1_:
![image](https://user-images.githubusercontent.com/34094951/34611470-e71b9f70-f225-11e7-931d-7b587f2b354c.png)

In de EAP van BeSt Add bijvoorbeeld (zie afbeelding 2) is de relatie Adres - Adresvoorstelling one-to-many. Dit is echter ook niet volledig conform, lijkt me, aangezien elk buitenlands adres uit Adresvoorstelling in die situatie dan gelinkt moet zijn met een Belgisch adres uit Adres. 

_afbeelding 2_:
![image](https://user-images.githubusercontent.com/34094951/34610781-e3fcd8ac-f222-11e7-9d7f-8d4a687e20aa.png)

**Comment by GeertThijs** [comment]
•	BestAdd is een model voor Belgische adressen, de AdressRepresentation kan maw enkel ve Belgisch adres zijn en moet dus verplicht verwijzen naar Address.
•	OSLO-Adres is iets ruimer opgevat, Adres is wel degelijk ook een Belgisch adres, maar de Adresvoorstelling kan ook op buitenlandse adressen slaan en dus is een relatie met Adres niet verplicht. 
•	De kardinaliteit waarover jij het hebt is die van heeftPostinfo, stond wat ongelukkig op de figuur. Op de verwijstNaar relatie stonden nog geen kardinaliteiten, dat heb ik intussen aangepast:
Voor:
![image](https://user-images.githubusercontent.com/22620291/34665064-2d31d7fa-f45f-11e7-8213-a5e352bbf4bb.png)
Na:
![image](https://user-images.githubusercontent.com/22620291/34665078-3a10bb12-f45f-11e7-852a-2cad3bd1119c.png)
