### ISSUE TITLE
OrganisatieAP: FormeleOrganisatie ontbreekt

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Vocabularia#7]
FormeleOrganisatie komt voor in de figuur, maar niet in de oplijsting van klassen.

http://data.vlaanderen.be/doc/applicatieprofiel/organisatie

**Comment by laurensdv** [comment]
Ga deze issue sluiten vermits het probleem algemener is dan enkel deze.
