### ISSUE TITLE
ATU codelijst

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO-Vocabularia#95]
In OSLO-Organisatie en OSLO-Dienst wordt verwezen naar de ATU codelijst, ttz de Administrative Territorial Units vd EU (zie https://data.europa.eu/euodp/nl/data/dataset/atu).
- Bij OSLO-Organisatie voor het attribuut werkingsgebied van PubliekeOrganisatie.
- Bij OSLO-Dienstverlening voor het attribuut ruimtelijkeDekking van PubliekeDienstverlening.

Echter: deze lijst is momenteel beperkt, voor België komen er enkel Gewesten, Gemeenschappen en Provincies in voor, maw deze lijst is praktisch niet bruikbaar.

**Comment by GeertThijs** [comment]
Alternatief hiervoor wordt voorgesteld door ISA in de ttl spec van CPSV-AP (opgelet, enkel in de ttl, niet in de doc of pdf !). Ipv naar administratieve eenheden te verwijzen verwijst men naar Places ipv' ATU's, zie http://publications.europa.eu/mdr/authority/place/index.html. Nadeel: geen gewesten, gemeenschappen of provincies in deze lijst, enkel plaatsnaemen - in praktijk deze vd Belgische gemeenten - zonder aanduiding vh administratief niveau. Ander alternatief, ook door ISA vermeld in de ttl, is geonames.org. Daar is het administratief niveau wel aanwezig.

**Comment by GeertThijs** [comment]
CONCLUSIE:

- We hernoemen de enumeratie ATU naar Plaatscode

- De bijbehorende ap-codelist tag veranderen we naar http://www.geonames.org/

**Comment by bertvannuffelen** [comment]
De PO heeft ook nog een andere NAL waarbij wel de regio's worden aangeduid:

http://publications.europa.eu/mdr/authority/atu/index.html

**Comment by GeertThijs** [comment]
- In Adres wordt niet naar een codelijst verwezen maar een associatie gelegd met een klasse AdministratieveEenheid. En het is daarvan dat dan Gemeentenaam is afgeleid, wat ook een klasse is.  
- Voor werkingsgebied en ruimtelijkeDekking wilden we naar analogie met ISA werken met een codelijst van AdministratieveEenheden, ATU. Maar die blijkt dus ontoereikend. 
- Geonames wordt zelf door ISA als alternatief genoemd. Daar gaat het wel over Plaats en Plaatsnaam, niet over AdministratieveEenheid.
- Twee verschillende concepten maar dat is geen probleem voor iets als werkingsgebied of ruimtelijkedekking (een ligging) maar wel voor Gemeentenaam.
- Voor geonames is inderdaad geen Belgisch alternatief, dat dan niet alleen administratieve eenheden als plaatsen mag bevatten.
- voor AdministratieveEenheid kunnen we volstaan met de identificator van de AdministratieveEenheid, dat is de NIScode.
